Repository RISHIT-ANAND/CP-GREEK, pull requests merged in 2023-10, with the labels that each got.

#13 Create q2.java
  QUESTION2/q2.java
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#15 Create q3.java
  QUESTION3/q3.java
Labels: hacktoberfest-accepted, hacktoberfest

#16 Create q4.java
  QUESTION4/q4.java
Labels: hacktoberfest-accepted, hacktoberfest

#17 Create q1-aditya.rs
  QUESTION1/aditya.rs
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#18 Create q2-aditya.rs
  QUESTION2/q2-aditya.rs
Labels: hacktoberfest-accepted, hacktoberfest

#19 Create q3-aditya.rs
  QUESTION3/q3-aditya.rs
Labels: hacktoberfest-accepted, hacktoberfest

#20 Create q4-aditya.rs
  QUESTION4/q4-aditya.rs
Labels: hacktoberfest-accepted, hacktoberfest

#14 Create K_Q3.c
  QUESTION3/K_Q3.c
Labels: hacktoberfest

#22 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#23 Create q1-kaif.c
  QUESTION1/q1-kaif.c
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#25 Create q2-kaif.c
  QUESTION2/q2-kaif.c
Labels: hacktoberfest-accepted, hacktoberfest

#27 Create q3-kaif.c
  QUESTION3/q3-kaif.c
Labels: hacktoberfest-accepted, hacktoberfest

#28 Create q4-kaif.c
  QUESTION4/q4-kaif.c
Labels: hacktoberfest-accepted, hacktoberfest

#24 Update K_Q1.py
  K_Q1.py
Labels: hacktoberfest-accepted, hacktoberfest

#26 Create pt2.py
  QUESTION2/pt2.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#30 Create pt3.py
  QUESTION3/pt3.py
Labels: hacktoberfest-accepted, hacktoberfest

#31 Create pt4.py
  QUESTION4/pt4.py
Labels: hacktoberfest-accepted, hacktoberfest
